//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kostuchenkoauthorization
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        internal readonly object PasswordBox;
        internal object TextBoxPassword;

        public long id { get; set; }
        public string login { get; set; }
        public string Password { get; set; }
        public string Role { get; set; }
    }
}
